apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: nginx-monitor
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: nginx-deploy
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
